### ISSUE TITLE
`delete` doesn't correctly select years within series

### ISSUE THREAD

**Issue by chguiterman** [ltrr-arizona-edu/burnr#123] opened 2019-01-28 14:40 UTC

**Comment by brews** [comment] 2019-01-28 22:42
Uh oh. Can you come up with a simple reproducible example?

**Comment by chguiterman** [comment] 2019-01-29 00:49
@brews -- well, what happens is that when you select multiple series and multiple years, `delete` removes all combinations  `yr` in `s`. I interpreted it as supposed to delete specific years from specific series, which it will if you only run the function on one series at a time. I was trying to remove years with injuries from an entire `fhx` object. It didn't do that correctly because it didn't index for each particular 's'. Subsetting (or filtering) the `fhx` object for my specific task was not that hard, though. 
So I'm not sure the function should change, but maybe it could use an edit to the description?

**Comment by brews** [comment] 2019-01-30 16:00
@chguiterman Okay, thanks for the info.

Just as a sanity check can you paste an example of the command/code you're running to `delete`? So, say if you have any old fhx object `d`, what are you writing on your terminal to delete from `d`.

**Comment by brews** [comment] 2019-07-09 20:15
The function appears to be working as intended. I'm marking this as invalid and closing.

Generally, for more complex tasks like this you might want to consider using `subset` rather than `delete`. For example, to remove all "fire-injury" records from the PGM example data, I recommend something like:

```R
library(burnr)
data(pgm)

injury_types <- c("unknown_fi", "dormant_fi", "early_fi", "middle_fi", "late_fi", "latewd_fi")

pgm_no_injuries <- subset(pgm, !(pgm$rec_type %in% injury_types))
# Because subset currently returns a data.frame rather than FHX object...
pgm_no_injuries <- fhx(pgm_no_injuries$year, pgm_no_injuries$series, pgm_no_injuries$rec_type)
```

...and boom goes the dynamite.

**Closed by brews** 2019-07-09 20:15 UTC
Labels: bug
