### ISSUE TITLE
Inform error message in `composite` for fhx with no scars

### ISSUE THREAD

**Issue by chguiterman** [ltrr-arizona-edu/burnr#155] opened 2019-08-06 22:14 UTC
If an `fhx` object ([like from this file](https://www.dropbox.com/s/xo31cf9d7wchbkv/usach005.fhx?dl=0)) contains no fire scars, `composite` throws an uninformative error:

```Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column```

This issue should be caught, flagged with a warning, and the composite should return an empty `fhx` object as is done when there are no events to composite.

**Comment by brews** [comment] 2019-08-07 18:18
Closing this issue because it is a duplicate of #131. This is fixed in `master` and will be part of the v0.0.5 release.

With the fix in #131, `composite()` it just returns an empty composite, without warning or message. Let me know if you have strong feelings otherwise.

**Comment by brews** [comment] 2019-08-07 18:39
Okay, I'm still getting the error with this file given as an example. I'm removing the duplicate tag and we'll see if we can't fix this for v0.0.5.

**Closed** 2019-08-07 20:11 UTC
Labels: bug, duplicate
